config/routes.rb
Rails.application.routes.draw do
  resources :product_reviews
  resources :products do
    collection do
      post 'parse_new'
    end
  end

  root 'products#index'

end

app/models/concerns/product_parser.rb
require 'net/http'
class ProductParser
  WALMART_API_URL = 'http://api.walmartlabs.com/v1/'

  def self.parse_new(url)
    new.parse_new(url)
  end

  # TODO: add some exception handling
  def parse_new(url)
    product = nil
    if (m = /\/(?<id>\d+)\?/.match(url))
      product_id = m['id']
      name, price = get_product_details(product_id)
      # TODO: add validation that product with such name is unique
      p = Product.new(name: name, price: price)
      # TODO: only new reviews should be here, they could be compared by content
      p.reviews = get_product_reviews(product_id)
      byebug
      product = p
    end
  end

  def get_product_details(product_id)
    # TODO: extract url preparation and request sending and response parsing to a method
    uri = URI(WALMART_API_URL)
    uri += "items/#{product_id}"
    params = { apiKey: api_key, format: 'json'}
    uri.query = URI.encode_www_form(params)

    resp = Net::HTTP.get_response uri
    result = JSON(resp.body)
    # TODO: condider saving product_id as well -- it could be easier to validate reviews with that
    [result['name'], result['salePrice']]
  end

  # TODO: as it turns out only 5 reviews could be received via API(https://developer.walmartlabs.com/forum/read/185226)
  #   Looks like parsing and paginating HTML on Customer Reviews page(e.g. https://www.walmart.com/reviews/product/54594376) 
  # is the only one way to go though such solution definitely doesn't look as a reliable & efficient
  def get_product_reviews(product_id)
    byebug
    uri = URI(WALMART_API_URL)
    uri += "reviews/#{product_id}"
    params = { apiKey: api_key, format: 'json'}
    uri.query = URI.encode_www_form(params)

    resp = Net::HTTP.get_response uri
    result = JSON(resp.body)
    # TODO: check if Product already exists(was fetched before), response has product name
    reviews = result['reviews'].map do |review|
      # TODO: it makes sense to get more data i.e. reviewer, title, upVotes etc.
      # TODO: skip adding review if such review already exist for a Product i.e. review was fetched before
      ProductReview.new(content: review['reviewText'])
    end
  end

  private
  def api_key
    # TODO: move it to some yml file
    '***'
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :reviews, class_name: 'ProductReview'
  # TODO: add unique index for name
end

app/models/product_review.rb
class ProductReview < ActiveRecord::Base
  # TODO: add index for content
  belongs_to :product
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/product_reviews_controller.rb
class ProductReviewsController < ApplicationController
  before_action :set_product_review, only: [:show, :edit, :update, :destroy]

  # GET /product_reviews
  # GET /product_reviews.json
  def index
    @product_reviews = ProductReview.all
  end

  # GET /product_reviews/1
  # GET /product_reviews/1.json
  def show
  end

  # GET /product_reviews/new
  def new
    @product_review = ProductReview.new
  end

  # GET /product_reviews/1/edit
  def edit
  end

  # POST /product_reviews
  # POST /product_reviews.json
  def create
    @product_review = ProductReview.new(product_review_params)

    respond_to do |format|
      if @product_review.save
        format.html { redirect_to @product_review, notice: 'Product review was successfully created.' }
        format.json { render :show, status: :created, location: @product_review }
      else
        format.html { render :new }
        format.json { render json: @product_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_reviews/1
  # PATCH/PUT /product_reviews/1.json
  def update
    respond_to do |format|
      if @product_review.update(product_review_params)
        format.html { redirect_to @product_review, notice: 'Product review was successfully updated.' }
        format.json { render :show, status: :ok, location: @product_review }
      else
        format.html { render :edit }
        format.json { render json: @product_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_reviews/1
  # DELETE /product_reviews/1.json
  def destroy
    @product_review.destroy
    respond_to do |format|
      format.html { redirect_to product_reviews_url, notice: 'Product review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_review
      @product_review = ProductReview.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_review_params
      params.require(:product_review).permit(:product_id, :content)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  def parse_new
    product = ProductParser.parse_new(params['t'])
    byebug
    respond_to do |format|
      if product&.save
        format.html { redirect_to product, notice: 'Product was successfully parsed.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { redirect_to products_path, notice: 'Some error happened during product parsing.' }
      end
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/product_reviews_helper.rb
module ProductReviewsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Smeller</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/product_reviews/_form.html.erb
<%= form_for(@product_review) do |f| %>
  <% if @product_review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product_review.errors.count, "error") %> prohibited this product_review from being saved:</h2>

      <ul>
      <% @product_review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.text_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/product_reviews/edit.html.erb
<h1>Editing Product Review</h1>

<%= render 'form' %>

<%= link_to 'Show', @product_review %> |
<%= link_to 'Back', product_reviews_path %>

app/views/product_reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Product Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @product_reviews.each do |product_review| %>
      <tr>
        <td><%= product_review.product_id %></td>
        <td><%= product_review.content %></td>
        <td><%= link_to 'Show', product_review %></td>
        <td><%= link_to 'Edit', edit_product_review_path(product_review) %></td>
        <td><%= link_to 'Destroy', product_review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product review', new_product_review_path %>

app/views/product_reviews/new.html.erb
<h1>New Product Review</h1>

<%= render 'form' %>

<%= link_to 'Back', product_reviews_path %>

app/views/product_reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @product_review.product_id %>
</p>

<p>
  <strong>Content:</strong>
  <%= @product_review.content %>
</p>

<%= link_to 'Edit', edit_product_review_path(@product_review) %> |
<%= link_to 'Back', product_reviews_path %>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<%= form_tag(controller: "products", action: "parse_new", method: "get") do %>
  <%= label_tag(:t, "URL:") %>
  <%= text_field_tag(:t) %>
  <%= submit_tag("Parse new product") %>
<% end %>
<br>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>